/*
 * AppBrain API
 *
 * API to interact with AppBrain.
 *
 * API version: 2.0
 * Contact: contact@appbrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about a library
type Library struct {
	// identifier for the library
	Id string `json:"id,omitempty"`
	// name of the library
	Name string `json:"name,omitempty"`
	// description of the library
	Description string `json:"description,omitempty"`
	// types of the library
	Types []string `json:"types,omitempty"`
	// tags associated with the library
	Tags []string `json:"tags,omitempty"`
	// official URL of the library
	OfficialUrl string `json:"officialUrl,omitempty"`
	// AppBrain URL of the library
	AppBrainUrl string `json:"appBrainUrl,omitempty"`
}
