/*
 * AppBrain API
 *
 * API to interact with AppBrain.
 *
 * API version: 2.0
 * Contact: contact@appbrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about a country
type CountryInfo struct {
	// country code
	Code string `json:"code,omitempty"`
	// name of the country
	Name string `json:"name,omitempty"`
	// minimum cost-per-install bid for app promotions in this country
	MinCpiBid float64 `json:"minCpiBid,omitempty"`
}
