/*
 * AppBrain API
 *
 * API to interact with AppBrain.
 *
 * API version: 2.0
 * Contact: contact@appbrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Settings for a country in the promotion campaign
type Country struct {
	// the two-letter ISO country code
	Code string `json:"code,omitempty"`
	// the maximum cost-per-install for a country in dollars
	Cpi float64 `json:"cpi,omitempty"`
}
