/*
 * AppBrain API
 *
 * API to interact with AppBrain.
 *
 * API version: 2.0
 * Contact: contact@appbrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// List of apps
type AppInfoList struct {
	// List of apps
	Apps []AppInfo `json:"apps,omitempty"`
}
